when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: 'TASK == "release-helper"'

steps:
  release-helper:
    image: docker.io/woodpeckerci/plugin-ready-release-go:2.1.1
    settings:
      git_email: woodpecker-bot@obermui.de
      forge_token:
        from_secret: gitea_token
