when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  release-helper:
    image: docker.io/woodpeckerci/plugin-ready-release-go:3.1.4
    settings:
      git_email: woodpecker-bot@obermui.de
      forge_token:
        from_secret: gitea_token
